# Site settings
title: Adrysson Lima
description: 'Web Developer'
url: 'http://adryssonlima.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Adrysson Lima'
  email: adrysson.lima@gmail.com
  twitter_username: adrysson_lima
  facebook_username: adryssonlima
  github_username: adryssonlima
  linkedin_username: adryssonlima

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
